
USE gctelecomdb
GO

-- INICIO PROCEDIMIENTOS ALMACENADOS PARA TABLA CLIENTES

-- SP_OBTENER_CLIENTES
IF EXISTS(SELECT * FROM sys.procedures WHERE NAME='SP_OBTENER_CLIENTES') 
	DROP PROCEDURE SP_OBTENER_CLIENTES
GO
CREATE PROC	SP_OBTENER_CLIENTES
	@es_visible INT = NULL
AS
BEGIN
	SELECT * FROM cliente WHERE (@es_visible IS NULL OR es_visible = @es_visible)
END
GO
	EXEC SP_OBTENER_CLIENTES
GO

-- SP_CREAR_CLIENTE
IF EXISTS(SELECT * FROM sys.procedures WHERE NAME='SP_CREAR_CLIENTE') 
	DROP PROCEDURE SP_CREAR_CLIENTE  
GO
CREATE PROC	SP_CREAR_CLIENTE
	@fuente_id INTEGER,
	@nombre VARCHAR(100),
	@correo VARCHAR(100),
	@celular VARCHAR(9),
	@direccion TEXT
AS
BEGIN
	BEGIN TRAN SP_CREAR_CLIENTE
	BEGIN TRY
		INSERT INTO cliente(fuente_id, nombre, correo, celular, direccion)
		VALUES(@fuente_id, @nombre, @correo, @celular, @direccion)
		COMMIT TRAN SP_CREAR_CLIENTE
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN SP_CREAR_CLIENTE
	END CATCH
END
GO

-- SP_ACTUALIZAR_CLIENTE
IF EXISTS(SELECT * FROM sys.procedures WHERE NAME='SP_ACTUALIZAR_CLIENTE') 
	DROP PROCEDURE SP_ACTUALIZAR_CLIENTE  
GO
CREATE PROC	SP_ACTUALIZAR_CLIENTE
	@cliente_id INTEGER,
	@fuente_id INTEGER,
	@nombre VARCHAR(100),
	@correo VARCHAR(100),
	@celular VARCHAR(9),
	@direccion TEXT
AS
BEGIN
	BEGIN TRAN SP_ACTUALIZAR_CLIENTE
	BEGIN TRY
		UPDATE cliente SET
			fuente_id=@fuente_id,
			nombre=@nombre,
			correo=@correo,
			celular=@celular,
			direccion=@direccion
		WHERE cliente_id=@cliente_id
		COMMIT TRAN SP_ACTUALIZAR_CLIENTE
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN SP_ACTUALIZAR_CLIENTE
	END CATCH
END
GO

-- SP_ACTIVAR_DESACTIVAR_CLIENTE
IF EXISTS(SELECT * FROM sys.procedures WHERE NAME='SP_ACTIVAR_DESACTIVAR_CLIENTE') 
	DROP PROCEDURE SP_ACTIVAR_DESACTIVAR_CLIENTE  
GO
CREATE PROC	SP_ACTIVAR_DESACTIVAR_CLIENTE
	@cliente_id INTEGER,
	@es_visible BIT
AS
BEGIN
	BEGIN TRAN SP_ACTIVAR_DESACTIVAR_CLIENTE
	BEGIN TRY
		UPDATE cliente SET es_visible=@es_visible WHERE cliente_id=@cliente_id
		COMMIT TRAN SP_ACTIVAR_DESACTIVAR_CLIENTE
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN SP_ACTIVAR_DESACTIVAR_CLIENTE
	END CATCH
END
GO

-- SP_OBTENER_SIGUIENTE_CLIENTE_ID
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'SP_OBTENER_SIGUIENTE_CLIENTE_ID')
    DROP PROCEDURE SP_OBTENER_SIGUIENTE_CLIENTE_ID;
GO

CREATE PROCEDURE SP_OBTENER_SIGUIENTE_CLIENTE_ID
AS
BEGIN
    DECLARE @siguiente_id INT;

    SELECT @siguiente_id = ISNULL(MAX(cliente_id), 0) + 1
    FROM cliente;

    SELECT @siguiente_id AS siguiente_cliente_id;
END;
GO

EXEC SP_OBTENER_SIGUIENTE_CLIENTE_ID
GO

-- FIN PROCEDIMIENTOS ALMACENADOS PARA TABLA CLIENTES

